- hosts: hadoop_slave
  tasks:
          - name: download JDK from FTP server
            copy:
                    src: "/root/jdk-8u171-linux-x64.rpm"
                    dest: "/root/"
          
          - name: install jdk
            command: "rpm -ivh /root/jdk-8u171-linux-x64.rpm"
            ignore_errors: yes
          
          - name: set java_home in bashrc file
            lineinfile:
                    path: /root/.bashrc
                    line: "export JAVA_HOME=/usr/java/jdk1.8.0_171-amd64/"
          
          - name: set path in bashrc file
            lineinfile:
                    path: /root/.bashrc
                    line: "PATH=/usr/java/jdk1.8.0_171-amd64/bin/:$PATH"
          
          - name: download Hadoop RPM from FTP server
            copy:
                    src: "/root/hadoop-1.2.1-1.x86_64.rpm"
                    dest: "/root/"
          
          - name: install hadoop rpm
            command: "rpm -ivh /root/hadoop-1.2.1-1.x86_64.rpm  --force"
          
          - name: create directory
            file:
                    path: "/data"
                    state: directory
          
          - name: configure hdfs file
            template:
                    src: "hdfs-site.xml.j2"
                    dest: "/etc/hadoop/hdfs-site.xml"
          
          - name: configure core-site file
            template:
                    src: "core-site.xml.j2"
                    dest: "/etc/hadoop/core-site.xml"
          
          - name: Stopping Firewall Services
            service:
                    name: firewalld
                    state: stopped
          
          - name: start datanode service
            command: "hadoop-daemon.sh  start  datanode"
            register: x
          
          - debug:
                  var: x
          
          - command: "jps"
            register: y
          
          - debug:
                  var: y
